---
- name: Launch the new EC2 Instance
  local_action: 
    module: ec2 
    group_id: "{{ webserver_firewall.group_id }}"
    instance_type: "{{ instance_type}}"
    image: "{{ ami_id }}"
    region: "{{ aws_region }}"
    count: "{{ count }}"
    key_name: "{{ key_name }}"
    wait: yes
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: 10
        delete_on_termination: true
    instance_tags:
      Name: aws-webserver
  register: ec2_webserver1

- debug: var=item.public_ip
  with_items: "{{ ec2_webserver1.instances }}"

- name: Add the newly created EC2 instance's IP to the local hosts file
  local_action: 
    module: lineinfile 
            dest="./inventory/hosts" 
            regexp={{ item.public_ip }}
            insertafter="[webserver]"
            line={{ item.public_ip }}
  with_items: "{{ ec2_webserver1.instances }}"
