---
- hosts: webservers
  remote_user: testuser1
  become: yes
  become_method: sudo

  tasks:
    # First update all existing packages (yum update)
    - name: Update packages
      yum: name=*
           update_cache=yes
           state=latest

    # Next, install Apache (httpd)
    - name: Install Apache
      yum: name=httpd
           update_cache=yes
           state=latest

    # Once Apache is installed, enable the service (`systemctl enable httpd`)
    - name: Enable Apache
      systemd: name=httpd
               state=started
               enabled=yes
      
      notify:
           - open_apache_port
           - open_apache_secure_port
           - restart_apache

  handlers:
    - name: open_apache_port
      firewalld: port=80/tcp
                 permanent=true
                 state=enabled
                 immediate=yes

    - name: open_apache_secure_port
      firewalld: port=443/tcp
                 permanent=true
                 state=enabled
                 immediate=true

    - name: restart_apache
      service: name=httpd
               state=restarted
